// Real browser UI measurements against the verified synthetic loopback fixture only.
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.VISITATION_PLAYWRIGHT_MODULE || '/opt/codex/cua_node/lib/node_modules/playwright');
const root=`${process.env.TEMP}/visitation-professional-preview`;
if(!JSON.parse(fs.readFileSync(`${root}/isolation.json`)).isolated_datadir_verified)throw new Error('Isolation not verified');
const before=process.argv[2]==='before',prefix=before?'visual-before':'visual-after',results=[],metrics=[],errors=[];
const browser=await chromium.launch({executablePath:process.env.VISITATION_CHROME || '/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext();await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:43417/')?r.continue():r.abort());
const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
const check=(name,passed)=>{results.push({check:name,passed});if(!passed&&!before)throw Error(name);};
const screenshot=tag=>page.screenshot({path:`${root}/${prefix}-${tag}.png`});
function luminance(c){return c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);}
function contrast(fg,bg){const [a,b]=[luminance(fg),luminance(bg)].sort((a,b)=>a-b);return (b+.05)/(a+.05);}
async function geometry(){return page.evaluate(()=>{const rect=selector=>{const e=document.querySelector(selector),r=e.getBoundingClientRect(),c=getComputedStyle(e);return {x:r.x,top:r.top,bottom:r.bottom,width:r.width,height:r.height,clientHeight:e.clientHeight,scrollHeight:e.scrollHeight,color:c.color,bg:c.backgroundColor}};return {sheet:rect('#sheet-place .bottom-sheet__inner'),actions:rect('.map-top-actions'),body:rect('#sheet-place .bottom-sheet__body'),footer:rect('#sheet-place .bottom-sheet__footer'),danger:rect('#btn-place-delete'),close:rect('#sheet-place .bottom-sheet__close'),overflow:document.documentElement.scrollWidth>innerWidth+1};});}
try{
 await page.goto('http://127.0.0.1:43417/login');await page.locator('#email').fill('admin@example.invalid');await page.locator('#password').fill('Preview-only-2026!');await page.locator('form button[type=submit]').click();await page.waitForURL('**/admin');
 for(const [width,height] of [[390,844],[320,568],[844,390],[568,320],[390,480],[1440,1000]]){
  await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:43417/app');await page.waitForFunction(()=>MapModule._markersById.size>=24);await page.evaluate(()=>MapModule._markersById.get(20).element.click());await page.waitForTimeout(300);
  const m={width,height,...await geometry()};metrics.push(m);await screenshot(`sheet-${width}x${height}`);
  check(`${width}x${height} info sheet leaves top actions visible`,m.sheet.top>=m.actions.bottom+10);check(`${width}x${height} info content has at least 44px visible`,m.body.height>=44);check(`${width}x${height} footer stays inside viewport`,m.footer.bottom<=height&&m.footer.top>=0);check(`${width}x${height} sheet has no horizontal overflow`,!m.overflow);
  m.dangerContrast=contrast(m.danger.color,m.danger.bg);m.closeContrast=contrast(m.close.color,'rgb(255, 255, 255)');check(`${width}x${height} danger text contrast >=4.5`,m.dangerContrast>=4.5);check(`${width}x${height} close text contrast >=4.5`,m.closeContrast>=4.5);
  await page.locator('#btn-place-detail').click();await page.waitForTimeout(250);let full=await geometry();check(`${width}x${height} expanded details keep controls visible`,full.sheet.top>=full.actions.bottom+10&&full.footer.bottom<=height&&full.body.height>=44);await screenshot(`details-${width}x${height}`);
  if(!before){await page.locator('#sheet-place .bottom-sheet__body').focus();await page.keyboard.press('End');await page.waitForTimeout(250);check(`${width}x${height} keyboard reaches lower details`,await page.locator('#sheet-place .bottom-sheet__body').evaluate(e=>e.scrollTop+e.clientHeight>=e.scrollHeight-2));check(`${width}x${height} expanded lower fields remain in scrollable region`,await page.locator('#sheet-place-details').getAttribute('aria-hidden')==='false');}
  await page.locator('#btn-place-edit').click();await page.waitForSelector('.modal--open');const c=await page.locator('.modal__close').evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {width:r.width,height:r.height,color:s.color,bg:s.backgroundColor}});m.modalClose=c;m.modalCloseContrast=contrast(c.color,'rgb(255, 255, 255)');check(`${width}x${height} form close target >=44px`,c.width>=44&&c.height>=44);check(`${width}x${height} form close text contrast >=4.5`,m.modalCloseContrast>=4.5);await screenshot(`form-${width}x${height}`);
  await page.keyboard.press('Escape');check(`${width}x${height} Escape cancels editor`,await page.locator('#modal-place-form').getAttribute('aria-hidden')==='true');
 }
 await page.setViewportSize({width:390,height:844});await page.locator('#btn-route-mode').click();await page.evaluate(()=>MapModule._markersById.get(1).element.click());await page.locator('#btn-route-expand').click();check('route exit uses a different visual role from clear',await page.locator('#btn-route-exit').evaluate(e=>e.classList.contains('btn-outline')&&!e.classList.contains('btn-danger'))&&await page.locator('#btn-route-clear').evaluate(e=>e.classList.contains('btn-danger')));
 await screenshot('route-actions');await page.locator('#btn-route-exit').click();check('route exit still retains selected destination',await page.locator('#route-badge').innerText()==='1');check('route exit still closes planning controls',await page.locator('#route-compact').evaluate(e=>e.hidden));
 if(!before){
  const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await touchContext.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:43417/')?r.continue():r.abort());const touchPage=await touchContext.newPage();touchPage.on('pageerror',e=>errors.push(String(e)));
  await touchPage.goto('http://127.0.0.1:43417/login');await touchPage.locator('#email').fill('admin@example.invalid');await touchPage.locator('#password').fill('Preview-only-2026!');await touchPage.locator('form button[type=submit]').tap();await touchPage.waitForURL('**/admin');await touchPage.goto('http://127.0.0.1:43417/app');await touchPage.waitForFunction(()=>MapModule._markersById.size>=24);await touchPage.evaluate(()=>MapModule._markersById.get(20).element.click());await touchPage.locator('#btn-place-edit').tap();await touchPage.waitForSelector('.modal--open');await touchPage.getByRole('button',{name:'關閉親訪表單',exact:true}).tap();check('emulated touch closes form through labelled 44px control',await touchPage.locator('#modal-place-form').getAttribute('aria-hidden')==='true');check('touch cancel restores body scrolling',await touchPage.evaluate(()=>!document.body.classList.contains('is-modal-open')));
  await touchPage.evaluate(()=>MapModule._markersById.get(20).element.click());await touchPage.getByRole('button',{name:'關閉親訪資訊',exact:true}).tap();check('emulated touch closes info through labelled control',await touchPage.locator('#sheet-place').evaluate(e=>!e.classList.contains('bottom-sheet--open')));await touchContext.close();
 }
 check('no browser runtime exceptions',errors.length===0);
}finally{fs.writeFileSync(`${root}/${prefix}-results.json`,JSON.stringify({syntheticOnly:true,results,metrics,errors},null,2));console.log(JSON.stringify({prefix,count:results.length,failed:results.filter(r=>!r.passed),errors},null,2));await browser.close();}
