// Native Chrome CDP and Node only. All requests target isolated loopback fixtures.
import fs from 'node:fs';
process.argv[2]='transfers-library';
const {call,evaluate,pause,navigate,screenshot,close,getBrowserErrors}=await import('./preview_browser.mjs');
const root=`${process.env.TEMP}/visitation-professional-preview`,results=[];
function check(name,value){if(!value)throw Error(name);results.push({check:name,passed:true});console.log('PASS',name);}
async function until(expr){for(let i=0;i<80;i++){if(await evaluate(expr))return;await pause(100);}throw Error('Timeout '+expr);}
async function input(id,value){await evaluate(`(()=>{let e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await pause(120);}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);await pause(100);let r=await evaluate(`(()=>{let r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...r});await call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...r});await pause(180);}
async function ready(){await until(`!document.querySelector('#transfer-refresh').disabled && !document.querySelector('#transfer-records').getAttribute('aria-busy').includes('true')`);}
async function login(email){await call('Network.clearBrowserCookies');await navigate('/login');check('synthetic login '+email,await evaluate(`(async()=>{let csrf=document.querySelector('meta[name="csrf-token"]').content;let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({email:${JSON.stringify(email)},password:'Preview-only-2026!'})});return r.ok})()`));}
async function profile(){await navigate('/profile');await ready();}
async function admin(){await navigate('/admin/transfers.php');await ready();}
async function request(){await input('request-organization','2');await input('request-reason','合成測試：因服務調整申請單位異動');await click('#request-submit');await ready();await until(`document.querySelector('[data-transfer-action="withdraw"]')`);}
async function confirm(reason){if(reason)await input('review-reason',reason);await click('#transfer-confirm-check');await click('#transfer-confirm-submit');await until(`!document.querySelector('#transfer-confirm').open`);await ready();}
async function overflow(label){check(label,await evaluate('document.documentElement.scrollWidth<=innerWidth+1'));}
try{
 await call('Network.enable');await call('Network.setBlockedURLs',{urls:['*maps.googleapis.com*','*unpkg.com*']});
 await login('user@example.invalid');await profile();await screenshot('transfer-user-desktop',1440,1000);await overflow('user desktop fits');
 check('active target choices only',await evaluate(`Array.from(document.querySelector('#request-organization').options).map(o=>o.value).sort().join(',')===',2,4'`));
 await click('#request-submit');check('required validation blocks empty request',await evaluate(`!document.querySelector('[data-transfer-action="withdraw"]') && !document.querySelector('#request-organization').checkValidity()`));
 await input('request-organization','2');await input('request-reason','合成測試：申請異動');
 await evaluate(`window.writeCount=0;window.savedFetch=fetch;window.fetch=((original)=>(...a)=>{if(a[1]?.method==='POST'&&String(a[0]).includes('organization-transfers'))writeCount++;return original(...a)})(fetch);document.querySelector('#transfer-request-form').requestSubmit();document.querySelector('#transfer-request-form').requestSubmit();`);
 await ready();await until(`document.querySelector('[data-transfer-action="withdraw"]')`);check('double request submits once',await evaluate('writeCount===1'));check('pending keeps current unit and disables second request',await evaluate(`document.querySelector('#current-organization').textContent==='示範服務中心'&&document.querySelector('#request-submit').disabled`));
 await screenshot('transfer-user-mobile',390,844);await overflow('390px user fits');
 await click('[data-transfer-action="withdraw"]');check('named withdrawal dialog',await evaluate(`document.querySelector('#transfer-confirm-title').textContent.includes('示範承辦人') && document.querySelector('#review-reason-label').hidden && getComputedStyle(document.querySelector('#review-reason-label')).display==='none'`));await screenshot('transfer-withdraw-mobile',390,844);
 await click('#transfer-cancel');check('cancel does not write',await evaluate(`!document.querySelector('#transfer-confirm').open && writeCount===1`));
 await click('[data-transfer-action="withdraw"]');await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await pause();check('Escape does not write',await evaluate(`!document.querySelector('#transfer-confirm').open&&writeCount===1`));
 await click('[data-transfer-action="withdraw"]');await click('#transfer-confirm-submit');check('checkbox prevents unconfirmed write',await evaluate(`document.querySelector('#transfer-confirm').open&&writeCount===1`));await confirm();check('withdrawal result visible',await evaluate(`document.querySelector('#transfer-records').textContent.includes('已撤回')`));await request();
 await login('admin@example.invalid');await admin();await screenshot('transfer-admin-desktop',1440,1000);await overflow('admin desktop fits');
 await click('[data-transfer-action="reject"]');await click('#transfer-confirm-check');await click('#transfer-confirm-submit');check('review requires reason',await evaluate(`document.querySelector('#transfer-confirm').open&&!document.querySelector('#review-reason').checkValidity()`));await input('review-reason','合成測試：資料需補充');await screenshot('transfer-review-mobile',390,844);await click('#transfer-cancel');check('review cancel keeps pending',await evaluate(`!!document.querySelector('[data-transfer-action="reject"]')`));
 await click('[data-transfer-action="reject"]');await confirm('合成測試：資料需補充');check('review queue empty after reject',await evaluate(`!document.querySelector('[data-transfer-action="reject"]')`));
 await login('user@example.invalid');await profile();check('user sees review reason',await evaluate(`document.querySelector('#transfer-records').textContent.includes('資料需補充')`));await request();
 await login('admin@example.invalid');await admin();await click('[data-transfer-action="approve"]');await input('review-reason','合成測試：調整已確認');await click('#transfer-confirm-check');
 await evaluate(`window.writeCount=0;window.savedFetch=fetch;window.fetch=((original)=>(...a)=>{if(a[1]?.method==='POST'&&String(a[0]).includes('organization-transfers'))writeCount++;return original(...a)})(fetch);document.querySelector('#transfer-confirm-form').requestSubmit();document.querySelector('#transfer-confirm-form').requestSubmit();`);await until(`!document.querySelector('#transfer-confirm').open`);await ready();check('double review submits once',await evaluate('writeCount===1'));check('approval audit visible',await evaluate(`document.querySelector('#transfer-audit').textContent.includes('申請核准')`));
 await input('queue-search','不存在的合成資料');await click('#queue-filter button');await ready();check('search has empty state',await evaluate(`document.querySelector('#transfer-records').textContent.includes('目前沒有')`));await input('queue-search','');await input('queue-status','ALL');await ready();check('status filter finds history',await evaluate(`document.querySelectorAll('.transfer-record[data-request-id]').length===3`));
 await input('adjust-user','2');await input('adjust-organization','1');await input('adjust-reason','合成測試：管理者直接調整');await click('#adjust-submit');check('direct dialog names account and units',await evaluate(`document.querySelector('#transfer-confirm-title').textContent.includes('示範承辦人')&&document.querySelector('#transfer-confirm-detail').textContent.includes('user@example.invalid')`));await screenshot('transfer-direct-mobile',390,844);await click('#transfer-cancel');await click('#adjust-submit');await confirm();check('direct audit visible',await evaluate(`document.querySelector('#transfer-audit').textContent.includes('直接調整')`));
 await screenshot('transfer-admin-mobile',390,844);await overflow('390px admin fits');await screenshot('transfer-admin-small',320,740);await overflow('320px admin fits');check('mobile buttons at least 44px',await evaluate(`Array.from(document.querySelectorAll('button')).filter(e=>e.getBoundingClientRect().height>0).every(e=>e.getBoundingClientRect().height>=44)`));
 await evaluate(`window.savedFetch=fetch;window.fetch=((original)=>(...a)=>{if(String(a[0]).includes('organization-transfers')&&(!a[1]||a[1].method!=='POST'))throw Error('合成測試讀取中斷');return original(...a)})(fetch)`);await click('#transfer-refresh');await ready();check('read failure visibly disables actions',await evaluate(`document.querySelector('#transfer-feedback').textContent.includes('重新整理')&&document.querySelector('#adjust-submit').disabled`));await evaluate('window.fetch=savedFetch');await click('#transfer-refresh');await ready();check('retry restores form',await evaluate(`!document.querySelector('#adjust-submit').disabled&&!document.querySelector('#transfer-feedback').classList.contains('is-error')`));
 await login('user@example.invalid');await profile();check('old login sees adjusted current unit',await evaluate(`document.querySelector('#current-organization').textContent==='示範服務中心'`));await screenshot('transfer-user-history-mobile',390,844);await overflow('mobile history fits');
 await click('a[href="/app"]');await until(`location.pathname==='/app' && document.querySelector('#nav-user-name')?.textContent.includes('示範承辦人')`);check('back to map retains compact mobile route',await evaluate(`document.querySelector('#route-compact').hidden`));

 await click('#btn-route-mode');await click('#btn-place-list');await until(`document.querySelectorAll('.place-list-item').length===2`);await click('.place-list-item');
 const cookies=new Map();async function outside(path,data,csrf){let r=await fetch('http://127.0.0.1:43417'+path,{method:data?'POST':'GET',headers:{Cookie:Array.from(cookies,([k,v])=>k+'='+v).join('; '),'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});for(let c of r.headers.getSetCookie()){let [k,v]=c.split(';')[0].split('=');cookies.set(k,v);}return r;}
 let html=await(await outside('/login')).text(),csrf=html.match(/name="csrf-token" content="([^"]+)"/)[1];check('independent synthetic reviewer login',(await outside('/api/auth/login',{email:'admin@example.invalid',password:'Preview-only-2026!'},csrf)).ok);
 let changed=await outside('/api/organization-transfers.php',{action:'adjust',user_id:2,organization_id:2,expected_organization_id:1,confirm_user_name:'示範承辦人',reason:'合成測試：登入中單位改變'},csrf);check('independent reviewer changes logged-in user scope',changed.ok);
 await evaluate(`window.dispatchEvent(new Event('focus'))`);await until(`document.querySelector('#nav-user-name')?.textContent.includes('示範承辦人') && !document.querySelector('#route-compact').hidden===false`);await pause(1500);await click('#btn-place-list');await until(`document.querySelectorAll('.place-list-item').length===1`);check('scope refresh removes old places and route',await evaluate(`document.querySelector('#place-list-items').textContent.includes('示範第二單位親訪點') && document.querySelector('#route-compact').hidden`));await screenshot('transfer-scope-map-mobile',390,844);
 check('browser no uncaught JavaScript exceptions',getBrowserErrors().length===0);
 fs.writeFileSync(`${root}/transfer-ui-results.json`,JSON.stringify(results,null,2));console.log('Transfer UI:',results.length,'checks passed');
}catch(e){console.error(e);console.log(await evaluate('({url:location.href,text:document.body.innerText.slice(0,2000)})'));await screenshot('transfer-qa-failure',390,844);fs.writeFileSync(`${root}/transfer-ui-results.json`,JSON.stringify({results,error:String(e),browserErrors:getBrowserErrors()},null,2));process.exitCode=1;}
finally{await call('Browser.close');close();}
