<?php $transferUser=current_user(); ?>
<!doctype html><html lang="zh-Hant">
<?php require __DIR__.'/head.php'; ?>
<body class="admin-body transfer-page" data-transfer-mode="<?= $transferAdmin?'admin':'user' ?>">
<a class="skip-link" href="#transfer-main">跳至主要內容</a>
<header class="admin-header"><div class="admin-brand"><span class="admin-app-name"><?= htmlspecialchars(APP_NAME,ENT_QUOTES,'UTF-8') ?></span><span class="admin-sub"><?= $transferAdmin?'單位異動管理':'我的單位' ?></span></div><nav class="admin-nav"><a class="btn-link" href="<?= route_url('app') ?>">回主地圖</a><?php if(is_admin()): ?><a class="btn-link" href="<?= route_url('admin') ?>">管理總覽</a><?php endif; ?></nav></header>
<main id="transfer-main" class="admin-main">
 <div class="admin-intro"><div><p class="eyebrow">服務人員管理</p><h1><?= $transferAdmin?'單位異動管理':'我的單位與異動申請' ?></h1><p>單位變更只調整帳戶的資料範圍，既有親訪紀錄保持原單位歸屬。</p></div><button id="transfer-refresh" type="button" class="btn-outline">重新整理</button></div>
 <div id="transfer-feedback" class="admin-feedback" role="status" aria-live="polite" hidden></div>
 <?php if(!$transferAdmin): ?>
 <section class="admin-tab-panel active"><h2>目前帳戶</h2><dl class="transfer-account"><div><dt>服務人員</dt><dd><?= htmlspecialchars($transferUser['name'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>目前單位</dt><dd id="current-organization"><?= htmlspecialchars($transferUser['organization_name']??'未指定',ENT_QUOTES,'UTF-8') ?></dd></div></dl></section>
 <section class="admin-tab-panel active" id="request-section"><h2>申請變更單位</h2><p id="pending-message" class="transfer-note">核准前仍使用目前單位的權限。一次僅能有一筆待審申請。</p><form id="transfer-request-form"><label>目標單位<select id="request-organization" required disabled><option value="">載入中…</option></select></label><label>申請原因<textarea id="request-reason" rows="3" required minlength="3" maxlength="1000" placeholder="請說明單位異動原因（3 至 1000 字）" disabled></textarea></label><button id="request-submit" type="submit" class="btn-primary" disabled>送出申請</button></form></section>
 <?php else: ?>
 <section class="admin-tab-panel active"><h2>直接調整一般使用者單位</h2><p class="transfer-note">僅限啟用的一般使用者，需具名確認及異動原因。若已有待審申請，直接調整會將該申請標記為「已由直接調整取代」，不會再核准舊申請。</p><form id="transfer-adjust-form"><div class="transfer-form-grid"><label>一般使用者<select id="adjust-user" required disabled><option value="">載入中…</option></select></label><label>新單位<select id="adjust-organization" required disabled><option value="">載入中…</option></select></label></div><label>異動原因<textarea id="adjust-reason" rows="2" required minlength="3" maxlength="1000" disabled></textarea></label><button id="adjust-submit" type="submit" class="btn-outline" disabled>確認調整對象</button></form></section>
 <?php endif; ?>
 <section class="admin-tab-panel active"><div class="section-heading"><h2><?= $transferAdmin?'申請審核':'我的申請與審核結果' ?></h2><span id="transfer-count" class="result-count"></span></div>
 <?php if($transferAdmin): ?><form id="queue-filter" class="transfer-form-grid"><label>申請狀態<select id="queue-status"><option value="PENDING">待審核</option><option value="ALL">所有狀態</option><option value="APPROVED">已核准</option><option value="REJECTED">已退回</option><option value="WITHDRAWN">已撤回</option><option value="SUPERSEDED">直接調整取代</option></select></label><label>搜尋姓名或單位<input id="queue-search" type="search" maxlength="100"></label><button type="submit" class="btn-outline">搜尋</button></form><?php endif; ?>
 <div id="transfer-records" aria-live="polite"><p class="empty-hint">載入中…</p></div><div class="transfer-pagination"><button id="history-prev" type="button" class="btn-outline" disabled>上一頁</button><span id="history-page"></span><button id="history-next" type="button" class="btn-outline" disabled>下一頁</button></div></section>
 <section class="admin-tab-panel active"><h2><?= $transferAdmin?'單位異動紀錄':'我的單位異動紀錄' ?></h2><p class="transfer-note">保留前後單位、操作者、原因與時間；審核核准及直接調整皆會留存。</p><div id="transfer-audit"></div><div class="transfer-pagination"><button id="audit-prev" type="button" class="btn-outline" disabled>上一頁</button><span id="audit-page"></span><button id="audit-next" type="button" class="btn-outline" disabled>下一頁</button></div></section>
</main>
<dialog id="transfer-confirm" class="admin-dialog" aria-labelledby="transfer-confirm-title"><form id="transfer-confirm-form"><h2 id="transfer-confirm-title"></h2><p id="transfer-confirm-detail"></p><label id="review-reason-label">審核原因<textarea id="review-reason" rows="3" minlength="3" maxlength="1000"></textarea></label><label class="transfer-confirm-check"><input id="transfer-confirm-check" type="checkbox" required>我已確認服務人員與單位異動內容</label><div class="dialog-actions"><button id="transfer-cancel" type="button" class="btn-outline">取消</button><button id="transfer-confirm-submit" type="submit" class="btn-primary">確認送出</button></div></form></dialog>
<script src="<?= asset_url('assets/js/api.js') ?>"></script><script src="<?= asset_url('assets/js/transfers.js') ?>"></script></body></html>
